import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider extends ChangeNotifier {
  String _currentLanguage = 'en'; // 'en', 'ta', 'ur'

  String get currentLanguage => _currentLanguage;

  LanguageProvider() {
    _loadLanguage();
  }

  Future<void> _loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    _currentLanguage = prefs.getString('app_language') ?? 'en';
    notifyListeners();
  }

  Future<void> changeLanguage(String languageCode) async {
    _currentLanguage = languageCode;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('app_language', languageCode);
    await prefs.setBool('has_seen_prayer_demo', false);
    notifyListeners();
  }

  // Helper method for translations
  String translate(String key) {
    return _translations[_currentLanguage]?[key] ?? _translations['en']?[key] ?? key;
  }

  // Helper method for localized rotating weekly messages
  List<String> getWeeklyMessages(String prayerName) {
    return _weeklyMessages[_currentLanguage]?[prayerName] ?? _weeklyMessages['en']?[prayerName] ?? [];
  }

  // Localized rotating weekly messages
  static const Map<String, Map<String, List<String>>> _weeklyMessages = {
    'en': {
      'Fajr': [
        "🕋 Fajr Reminder\nAssalamu Alaikum. It is time for Fajr prayer. Rise for the remembrance of Allah and begin your day with Salah.",
        "🌄 Wake for Fajr\nWake up and answer the call of Allah. As-salātu khayrun minan-nawm (Prayer is better than sleep).",
        "🤲 Start with Allah\nBegin your day by performing Fajr prayer and seeking Allah's guidance and blessings.",
        "📿 Don't Delay Fajr\nEvery sunrise is a blessing. Offer your Fajr Salah with sincerity and devotion.",
        "🌙 Blessed Morning\nThe best way to begin your morning is with the remembrance of Allah through Fajr prayer.",
        "❤️ Seek Allah's Mercy\nPerform Fajr on time and ask Allah to grant you success, health, and peace throughout the day.",
        "✨ Morning of Faith\nMay your Fajr prayer fill your heart with light and bring barakah to your entire day.",
      ],
      'Dhuhr': [
        "🕌 Dhuhr Reminder\nAssalamu Alaikum. It is time for Dhuhr prayer. Pause your work and answer Allah's call.",
        "🤲 Time for Dhuhr\nLeave your worldly tasks for a few moments and stand before Allah in prayer.",
        "📿 Midday Salah\nPerform your Dhuhr prayer on time and seek Allah's forgiveness and mercy.",
        "🌿 Remember Allah\nRefresh your heart with the remembrance of Allah through Dhuhr Salah.",
        "🕋 Answer the Adhan\nRespond to the call to prayer and perform your Dhuhr Salah with humility.",
        "🕌 Jummah Reminder\nAssalamu Alaikum. Today is Friday, the blessed day of Jummah. Prepare for Jummah prayer, make du'a, and recite Surah Al-Kahf.",
        "❤️ Peace Through Prayer\nMay Allah accept your Dhuhr prayer and bless the rest of your day.",
      ],
      'Asr': [
        "🕌 Asr Reminder\nAssalamu Alaikum. It is time for Asr prayer. Do not delay your Salah.",
        "🤲 Time for Asr\nRemember Allah before the day comes to an end and perform your Asr prayer.",
        "📿 Afternoon Prayer\nOffer your Asr Salah with sincerity and gratitude.",
        "🌅 Protect Your Prayer\nProtect your prayers, especially Asr, and seek Allah's mercy.",
        "🕋 Stand Before Allah\nPause your daily work and devote these moments to worship.",
        "❤️ Seek Forgiveness\nAsk Allah to forgive your shortcomings and accept your Asr prayer.",
        "✨ Faith Until Sunset\nKeep your heart connected to Allah by performing Asr on time.",
      ],
      'Maghrib': [
        "🕌 Maghrib Reminder\nAssalamu Alaikum. The sun has set. It is time for Maghrib prayer.",
        "🌇 Sunset Prayer\nThank Allah for the blessings of today and perform your Maghrib Salah.",
        "🤲 Time for Maghrib\nEnd the day with gratitude by remembering Allah through prayer.",
        "📿 Evening Worship\nOffer your Maghrib prayer promptly and seek Allah's forgiveness.",
        "🌙 Blessed Evening\nFill your evening with the remembrance of Allah and sincere worship.",
        "🕋 Answer Allah's Call\nPerform Maghrib prayer with humility and thank Allah for His countless blessings.",
        "❤️ Peace at Sunset\nMay Allah accept your Maghrib prayer and fill your heart with peace.",
      ],
      'Isha': [
        "🕌 Isha Reminder\nAssalamu Alaikum. It is time for Isha prayer. End your day with the remembrance of Allah.",
        "🤲 Night Prayer\nPerform your Isha Salah before resting and seek Allah's forgiveness.",
        "📿 Complete Your Day\nEnd your day with Isha prayer and place your trust in Allah.",
        "🌙 Before Sleeping\nPray Isha, make du'a, and ask Allah for protection throughout the night.",
        "🕋 Night of Worship\nComplete your daily prayers with Isha and seek Allah's mercy.",
        "❤️ Rest with Peace\nMay Allah forgive your sins, accept your Isha prayer, and grant you peaceful sleep.",
        "✨ Sleep in Allah's Protection\nEnd your day in worship, remembering Allah and trusting in His care. May He grant you a blessed night. Āmīn.",
      ],
    },
    'ta': {
      'Fajr': [
        "🕌 ஃபஜ்ர் நினைவூட்டல்\nஅஸ்ஸலாமு அலைக்கும். ஃபஜ்ர் தொழுகைக்கான நேரம் இது. அல்லாஹ்வின் நினைவோடு எழுந்து உங்கள் நாளை தொழுகையுடன் தொடங்குங்கள்.",
        "🌄 ஃபஜ்ருக்காக எழுங்கள்\nவிழித்தெழுந்து அல்லாஹ்வின் அழைப்பிற்கு பதிலளிக்கவும். தொழுகை தூக்கத்தை விட சிறந்தது (அஸ்ஸலாது கைருன் மினன் நவ்ம்).",
        "🤲 அல்லாஹ்வுடன் தொடங்குங்கள்\nஃபஜ்ர் தொழுகையை நிறைவேற்றி, அல்லாஹ்வின் வழிகாட்டுதலையும் ஆசீர்வாதங்களையும் தேடி உங்கள் நாளைத் தொடங்குங்கள்.",
        "📿 ஃபஜ்ரை தாமதிக்க வேண்டாம்\nஒவ்வொரு சூரிய உதயமும் ஒரு வரப்பிரசாதம். உங்கள் ஃபஜ்ர் தொழுகையை நேர்மையுடனும் பக்தியுடனும் நிறைவேற்றுங்கள்.",
        "🌙 ஆசீர்வதிக்கப்பட்ட காலை\nஉங்கள் காலையைத் தொடங்குவதற்கான மிகச் சிறந்த வழி, ஃபஜ்ர் தொழுகையின் மூலம் அல்லாஹ்வை நினைவுகூருவதே ஆகும்.",
        "❤️ அல்லாஹ்வின் அருளைத் தேடுங்கள்\nஃபஜ்ரை சரியான நேரத்தில் தொழுது, நாள் முழுவதும் வெற்றி, ஆரோக்கியம் மற்றும் அமைதியைத் தருமாறு அல்லாஹ்விடம் கேளுங்கள்.",
        "✨ ஈமானின் காலை\nஉங்கள் ஃபஜ்ர் தொழுகை உங்கள் இதயத்தை ஒளியால் நிரப்பி, நாள் முழுவதற்கும் பரக்கத்தை கொண்டு வரட்டும்.",
      ],
      'Dhuhr': [
        "🕌 ளுஹர் நினைவூட்டல்\nஅஸ்ஸலாமு அலைக்கும். ளுஹர் தொழுகைக்கான நேரம் இது. உங்கள் வேலையை சற்று நிறுத்தி அல்லாஹ்வின் அழைப்பிற்கு பதிலளிக்கவும்.",
        "🤲 ளுஹருக்கான நேரம்\nஉங்கள் உலகியல் பணிகளை சில நிமிடங்கள் ஒதுக்கி வைத்து விட்டு, தொழுகையில் அல்லாஹ்வின் முன் நில்லுங்கள்.",
        "📿 மதிய தொழுகை\nஉங்கள் ளுஹர் தொழுகையை சரியான நேரத்தில் நிறைவேற்றி அல்லாஹ்வின் மன்னிப்பையும் கிருபையையும் தேடுங்கள்.",
        "🌿 அல்லாஹ்வை நினைவுகூருங்கள்\nளுஹர் தொழுகையின் மூலம் அல்லாஹ்வின் நினைவால் உங்கள் இதயத்தை புத்துணர்ச்சியாக்குங்கள்.",
        "🕋 பாங்கிற்கு பதிலளிக்கவும்\nதொழுகைக்கான அழைப்பிற்கு பதிலளித்து, உங்கள் ளுஹர் தொழுகையை பணிவுடன் நிறைவேற்றுங்கள்.",
        "🕌 ஜும்மா நினைவூட்டல்\nஅஸ்ஸலாமு அலைக்கும். இன்று ஜும்மாவின் ஆசீர்வதிக்கப்பட்ட வெள்ளிக்கிழமை. ஜும்மா தொழுகைக்கு தயாராகுங்கள், துஆ செய்யுங்கள், மற்றும் சூரா அல்-கஹ்ஃப் ஓதுங்கள்.",
        "❤️ தொழுகையின் மூலம் அமைதி\nஅல்லாஹ் உங்கள் ளுஹர் தொழுகையை ஏற்றுக்கொண்டு, உங்கள் நாளின் எஞ்சிய பகுதியை ஆசீர்வதிப்பாராக.",
      ],
      'Asr': [
        "🕌 அஸர் நினைவூட்டல்\nஅஸ்ஸலாமு அலைக்கும். அஸர் தொழுகைக்கான நேரம் இது. உங்கள் தொழுகையை தாமதப்படுத்த வேண்டாம்.",
        "🤲 அஸருக்கான நேரம்\nபகல் பொழுது முடிவதற்குள் அல்லாஹ்வை நினைவுகூர்ந்து உங்கள் அஸர் தொழுகையை நிறைவேற்றுங்கள்.",
        "📿 மாலை நேரத் தொழுகை\nஉங்கள் அஸர் தொழுகையை நேர்மையுடனும் நன்றியுடனும் நிறைவேற்றுங்கள்.",
        "🌅 தொழுகையைப் பேணுங்கள்\nஉங்கள் தொழுகைகளை, குறிப்பாக அஸர் தொழுகையைப் பேணி பாதுகாத்து, அல்லாஹ்வின் கிருபையைத் தேடுங்கள்.",
        "🕋 அல்லாஹ்வின் முன் நில்லுங்கள்\nஉங்கள் அன்றாட வேலைகளை நிறுத்திவிட்டு இந்த தருணங்களை வழிபாட்டிற்கு அர்ப்பணியுங்கள்.",
        "❤️ மன்னிப்புத் தேடுங்கள்\nஉங்கள் குறைகளை மன்னித்து, உங்கள் அஸர் தொழுகையை ஏற்றுக்கொள்ளுமாறு அல்லாஹ்விடம் கேளுங்கள்.",
        "✨ அந்தி வரை ஈமான்\nஅஸர் தொழுகையை சரியான நேரத்தில் நிறைவேற்றுவதன் மூலம் உங்கள் இதயத்தை அல்லாஹ்வோடு இணைந்திருக்கச் செய்யுங்கள்."
      ],
      'Maghrib': [
        "🕌 மக்ரிப் நினைவூட்டல்\nஅஸ்ஸலாமு அலைக்கும். சூரியன் மறைந்துவிட்டது. மக்ரிப் தொழுகைக்கான நேரம் இது.",
        "🌇 அந்தி நேரத் தொழுகை\nஇன்றைய நாளின் அருட்கொடைகளுக்காக அல்லாஹ்வுக்கு நன்றி கூறி, உங்கள் மக்ரிப் தொழுகையை நிறைவேற்றுங்கள்.",
        "🤲 மக்ரிப்கான நேரம்\nதொழுகையின் மூலம் அல்லாஹ்வை நினைவுகூர்ந்து நன்றியுடன் இந்த நாளை நிறைவு செய்யுங்கள்.",
        "📿 மாலை நேர வழிபாடு\nஉங்கள் மக்ரிப் தொழுகையை உடனடியாக நிறைவேற்றி அல்லாஹ்வின் மன்னிப்பைத் தேடுங்கள்.",
        "🌙 ஆசீர்வதிக்கப்பட்ட மாலை\nஉங்கள் மாலைப் பொழுதை அல்லாஹ்வின் நினைவாலும் நேர்மையான வழிபாட்டாலும் நிரப்புங்கள்.",
        "🕋 Answer Allah's Call\nPerform Maghrib prayer with humility and thank Allah for His countless blessings.",
        "❤️ மாலை அமைதி\nஅல்லாஹ் உங்கள் மக்ரிப் தொழுகையை ஏற்றுக்கொண்டு உங்கள் இதயத்தை அமைதியால் நிரப்புவாராக.",
      ],
      'Isha': [
        "🕌 இஷா நினைவூட்டல்\nஅஸ்ஸலாமு அலைக்கும். இஷா தொழுகைக்கான நேரம் இது. அல்லாஹ்வின் நினைவோடு உங்கள் நாளை நிறைவு செய்யுங்கள்.",
        "🤲 இரவுத் தொழுகை\nஓய்வெடுப்பதற்கு முன் உங்கள் இஷா தொழுகையை நிறைவேற்றி அல்லாஹ்வின் மன்னிப்பைத் தேடுங்கள்.",
        "📿 உங்கள் நாளை நிறைவு செய்யுங்கள்\nஉங்கள் நாளை இஷா தொழுகையுடன் முடித்து அல்லாஹ்வின் மீது உங்கள் நம்பிக்கையை வையுங்கள்.",
        "🌙 உறங்குவதற்கு முன்\nஇஷா தொழுது, துஆ செய்து, இரவு முழுவதும் அல்லாஹ்விடம் பாதுகாப்பு கேளுங்கள்.",
        "🕋 வழிபாட்டு இரவு\nஇஷா தொழுகையுடன் உங்கள் அன்றாட கடமைகளை முடித்து அல்லாஹ்வின் கருணையைத் தேடுங்கள்.",
        "❤️ அமைதியான ஓய்வு\nஅல்லாஹ் உங்கள் பாவங்களை மன்னித்து, இஷா தொழுகையை ஏற்று, உங்களுக்கு அமைதியான தூக்கத்தை தருவாராக.",
        "✨ அல்லாஹ்வின் பாதுகாப்பில் உறங்குங்கள்\nஉங்கள் நாளை வழிபாட்டிலும் அல்லாஹ்வின் நினைவிலும் முடித்து அவனது பாதுகாப்பை நம்புங்கள். அவன் உங்களுக்கு ஒரு ஆசீர்வதிக்கப்பட்ட இரவை வழங்குவானாக. ஆமீன்.",
      ],
    },
    'ur': {
      'Fajr': [
        "🕌 فجر ریمائنڈر\nالسلام علیکم۔ یہ فجر کی نماز کا وقت ہے۔ اللہ کی یاد کے لیے اٹھیں اور اپنے دن کا آغاز نماز سے کریں۔",
        "🌄 فجر کے لیے بیدار ہوں\nجاگیں اور اللہ کی پکار کا جواب دیں۔ الصلاۃ خیر من النوم (نماز نیند سے بہتر ہے)۔",
        "🤲 اللہ کے نام سے آغاز\nفجر کی نماز ادا کر کے اور اللہ کی رہنمائی اور برکات حاصل کر کے اپنے دن کا آغاز کریں۔",
        "📿 فجر میں تاخیر نہ کریں\nہر طلوع آفتاب ایک نعمت ہے۔ اپنی فجر کی نماز خلوص اور عقیدت کے ساتھ ادا کریں۔",
        "🌙 بابرکت صبح\nاپنی صبح کا آغاز کرنے کا بہترین طریقہ فجر کی نماز کے ذریعے اللہ کو یاد کرنا ہے۔",
        "❤️ اللہ کی رحمت تلاش کریں\nفجر وقت پر ادا کریں اور اللہ سے دن بھر کامیابی، صحت اور امن عطا کرنے کی دعا کریں۔",
        "✨ ایمان کی صبح\nاللہ کرے آپ کی فجر کی نماز آپ کے دل کو نور سے بھر دے اور آپ کے پورے دن میں برکت لائے۔",
      ],
      'Dhuhr': [
        "🕌 ظہر ریمائنڈر\nالسلام علیکم۔ یہ ظہر کی نماز کا وقت ہے۔ اپنا کام کچھ دیر روکیں اور اللہ کی پکار کا جواب دیں۔",
        "🤲 ظہر کا وقت\nاپنے دنیاوی کاموں کو چند لمحوں کے لیے چھوڑ دیں اور نماز میں اللہ کے حضور کھڑے ہو جائیں۔",
        "📿 دوپہر کی نماز\nاپنی ظہر کی نماز وقت پر ادا کریں اور اللہ کی بخشش اور رحمت طلب کریں۔",
        "🌿 اللہ کو یاد رکھیں\nظہر کی نماز کے ذریعے اللہ کے ذکر سے اپنے دل کو تازہ کریں۔",
        "🕋 اذان کا جواب دیں\nاذان کی پکار کا جواب دیں اور عاجزی کے ساتھ ظہر کی نماز ادا کریں۔",
        "🕌 جمعہ کی یاد دہانی\nالسلام علیکم۔ آج جمعہ کا بابرکت دن ہے۔ جمعہ کی نماز کی تیاری کریں، دعا کریں اور سورہ کہف کی تلاوت کریں۔",
        "❤️ نماز کے ذریعے سکون\nاللہ آپ کی ظہر کی نماز قبول فرمائے اور آپ کے باقی دن میں برکت عطا فرمائے۔",
      ],
      'Asr': [
        "🕌 عصر ریمائنڈر\nالسلام علیکم۔ یہ عصر کی نماز کا وقت ہے۔ اپنی نماز میں تاخیر نہ کریں۔",
        "🤲 عصر کا وقت\nدن ختم ہونے سے پہلے اللہ کو یاد کریں اور اپنی عصر کی نماز ادا کریں۔",
        "📿 دوپہر کے بعد کی نماز\nاپنی عصر کی نماز خلوص اور شکر گزاری کے ساتھ ادا کریں۔",
        "🌅 اپنی نماز کی حفاظت کریں\nاپنی نمازوں کی حفاظت کریں، خصوصاً عصر کی، اور اللہ کی رحمت طلب کریں۔",
        "🕋 اللہ کے حضور کھڑے ہوں\nاپنے روزمرہ کے کام کو روکیں اور ان لمحات کو عبادت کے لیے وقف کریں۔",
        "❤️ معافی مانگیں\nاللہ سے اپنی کوتاہیوں کی معافی مانگیں اور اپنی عصر کی نماز کی قبولیت کی دعا کریں۔",
        "✨ غروب آفتاب تک ایمان\nعصر وقت پر ادا کر کے اپنے دل کو اللہ سے جوڑے رکھیں۔",
      ],
      'Maghrib': [
        "🕌 مغرب ریمائنڈر\nالسلام علیکم۔ سورج غروب ہو چکا ہے۔ یہ مغرب کی نماز کا وقت ہے۔",
        "🌇 غروب آفتاب کی نماز\nآج کی نعمتوں پر اللہ کا شکر ادا کریں اور اپنی مغرب کی نماز ادا کریں۔",
        "🤲 مغرب کا وقت\nنماز کے ذریعے اللہ کو یاد کر کے شکر گزاری کے ساتھ دن کا اختتام کریں۔",
        "📿 شام کی عبادت\nاپنی مغرب کی نماز فوری ادا کریں اور اللہ سے مغفرت طلب کریں۔",
        "🌙 بابرکت شام\nاپنی شام کو اللہ کے ذکر اور خلوص نیت کے ساتھ عبادت سے بھریں۔",
        "🕋 اللہ کی پکار کا جواب دیں\nعاجزی کے ساتھ مغرب کی نماز ادا کریں اور اللہ کی ان گنت نعمتوں پر اس کا شکر ادا کریں۔",
        "❤️ غروب آفتاب پر سکون\nاللہ آپ کی مغرب کی نماز قبول فرمائے اور آپ کے دل کو سکون سے بھر دے۔",
      ],
      'Isha': [
        "🕌 عشاء ریمائنڈر\nالسلام علیکم۔ یہ عشاء کی نماز کا وقت ہے۔ اپنے دن کا اختتام اللہ کے ذکر سے کریں۔",
        "🤲 رات کی نماز\nآرام کرنے سے پہلے اپنی عشاء کی نماز ادا کریں اور اللہ سے مغفرت طلب کریں۔",
        "📿 اپنے دن کو مکمل کریں\nعشاء کی نماز کے ساتھ اپنے دن کا اختتام کریں اور اللہ پر اپنا توکل رکھیں۔",
        "🌙 سونے سے پہلے\nعشاء کی نماز پڑھیں، دعا مانگیں، اور رات بھر اللہ سے حفاظت کی التجا کریں۔",
        "🕋 عبادت کی رات\nاپنی عشاء کے ساتھ دن بھر کی نمازیں مکمل کریں اور اللہ کی رحمت طلب کریں۔",
        "❤️ سکون کے ساتھ آرام\nاللہ آپ کے گناہ معاف فرمائے، عشاء کی نماز قبول کرے اور پرسکون نیند عطا کرے۔",
        "✨ اللہ کی حفاظت میں سوئیں\nاپنے دن کا اختتام عبادت پر کریں، اللہ کو یاد رکھیں اور اس کی حفاظت پر بھروسہ کریں۔ وہ آپ کو ایک بابرکت رات عطا فرمائے۔ آمین۔",
      ],
    }
  };

  // Pre-defined translation map
  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'app_title': 'Reminder App',
      'prayer_planner': 'Prayer Planner',
      'workout_planner': 'Workout Planner',
      'meal_planner': 'Meal Planner',
      'medicine_planner': 'Medicine Planner',
      'study_planner': 'Study Planner',
      'snacks_planner': 'Study Planner',
      'sleeping_planner': 'Sleeping Planner',
      'about_app': 'About App',
      'guide': 'Guide',
      'enable_auto_location': 'Auto Location',
      'disable_auto_location': 'Disable Auto Location',
      'refresh_prayer_times': 'Refresh Times',
      'auto_open_on_ring': 'Auto Open on Ring',
      'no_reminders_yet': 'No Reminders Yet!',
      'sunrise': 'Sunrise',
      'next_prayer': 'Next Prayer',
      'save': 'Save',
      'cancel': 'Cancel',
      'name': 'Name',
      'time': 'Time',
      'message': 'Message',
      'repeat_days': 'Repeat Days',
      'add_reminder': 'Add Reminder',
      'edit_reminder': 'Edit Reminder',
      'delete_reminder': 'Delete Reminder',
      'select_sound': 'Select Sound',
      'done': 'Done',
      'language': 'Language',
      'select_language': 'Select Language',
      'Fajr': 'Fajr',
      'Dhuhr': 'Dhuhr',
      'Asr': 'Asr',
      'Maghrib': 'Maghrib',
      'Isha': 'Isha',
      'Sunrise': 'Sunrise',
      'reminder_deleted': 'Reminder deleted',
      'guide_title': 'Prayer Planner Guide',
      'guide_step1_title': 'Auto-Location',
      'guide_step1_desc': 'Tap the top location card or menu to enable Auto Location for accurate local prayer times.',
      'guide_step2_title': 'Prayer Alarms',
      'guide_step2_desc': 'Toggle the switches on the right to turn notifications on or off for each prayer.',
      'guide_step3_title': 'Change Time',
      'guide_step3_desc': 'Tap any prayer row to manually adjust the alarm time.',
      'guide_step4_title': 'Edit Message',
      'guide_step4_desc': 'Long press any prayer row to customize the message or select rotating weekly messages.',
      'got_it': 'Got it!',
      'auto_message': 'Auto Message',
      'custom_message': 'Custom Message',
      'auto_location_enabled': 'Auto Location Enabled',
      'auto_location_disabled': 'Auto Location Disabled',
      'last_updated': 'Last Updated',
      'sound_changed': 'Sound changed to',
      'not_updated_yet': 'Not updated yet',
      'updated': 'Updated',
      'required_fields': 'Please fill in all required fields',
      'message_optional': 'Message (Optional)',
      'repeat_pattern': 'Repeat Pattern',
      'Daily': 'Daily',
      'Weekdays': 'Weekdays',
      'Weekends': 'Weekends',
      'Custom': 'Custom',
      'select_time': 'Select Time',
      'add': 'Add',
      'reminder_name': 'Reminder Name',
      'notification_sound': 'Notification Sound',
      'perform_prayer': 'Perform Prayer',
      'fix_sound': 'Fix Alarm Sound',
      'open_settings': 'Open Settings',
      'guide_step5_title': 'Sound Settings',
      'guide_step5_desc': 'If your alarms are silent, open settings and ensure "Allow playing sound" is turned ON.',
      'prayer_location_heading': 'Prayer Times & Location',
      'tap_to_enable_location': 'Tap to enable location & fetch times',
      'refreshing_location_prayer_times': 'Refreshing location & prayer times...',
      'prayer_subtitle': 'Daily prayer times & Azan reminders',
      'workout_subtitle': 'Fitness & exercise schedules',
      'meal_subtitle': 'Nutrition & diet reminders',
      'medicine_subtitle': 'Pills & health tracking',
      'study_subtitle': 'Study, reading & exam schedules',
      'sleep_subtitle': 'Bedtime & sleep cycle schedule',
      'confirm_delete': 'Are you sure you want to delete',
      'delete': 'Delete',
      'setup_sample_planner': 'Set Up Sample Planner',
      'clear_all': 'Clear All Reminders',
      'sample_planner_loaded': 'Sample planner loaded successfully!',
      'load_sample_reminders': 'Load Sample Reminders',
      'samples_already_added': 'Sample reminders are already added',
    },
    'ta': {
      'app_title': 'நினைவூட்டல் செயலி',
      'prayer_planner': 'தொழுகை நினைவூட்டல்',
      'workout_planner': 'உடற்பயிற்சி நினைவூட்டல்',
      'meal_planner': 'உணவு நினைவூட்டல்',
      'medicine_planner': 'மருந்து நினைவூட்டல்',
      'study_planner': 'படிப்பு நினைவூட்டல்',
      'snacks_planner': 'படிப்பு நினைவூட்டல்',
      'sleeping_planner': 'தூக்க நினைவூட்டல்',
      'about_app': 'செயலியைப் பற்றி',
      'guide': 'வழிகாட்டி',
      'enable_auto_location': 'தானியங்கி இருப்பிடம்',
      'disable_auto_location': 'தானியங்கி இருப்பிடத்தை முடக்கு',
      'refresh_prayer_times': 'புதுப்பித்தல்',
      'auto_open_on_ring': 'தானாக திறக்க',
      'no_reminders_yet': 'நினைவூட்டல்கள் எதுவும் இல்லை!',
      'sunrise': 'சூரிய உதயம்',
      'next_prayer': 'அடுத்த தொழுகை',
      'save': 'சேமி',
      'cancel': 'ரத்து',
      'name': 'பெயர்',
      'time': 'நேரம்',
      'message': 'செய்தி',
      'repeat_days': 'நாட்கள்',
      'add_reminder': 'நினைவூட்டலைச் சேர்',
      'edit_reminder': 'நினைவூட்டலைத் திருத்து',
      'delete_reminder': 'நினைவூட்டலை நீக்கு',
      'select_sound': 'ஒலியைத் தேர்ந்தெடு',
      'done': 'முடிந்தது',
      'language': 'மொழி',
      'select_language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'Fajr': 'ஃபஜ்ர்',
      'Dhuhr': 'ளுஹர்',
      'Asr': 'அஸர்',
      'Maghrib': 'மக்ரிப்',
      'Isha': 'இஷா',
      'Sunrise': 'சூரிய உதயம்',
      'reminder_deleted': 'நினைவூட்டல் நீக்கப்பட்டது',
      'guide_title': 'தொழுகை வழிகாட்டி',
      'guide_step1_title': 'தானியங்கி இருப்பிடம்',
      'guide_step1_desc': 'துல்லியமான உள்ளூர் தொழுகை நேரங்களை அமைக்க மேலேயுள்ள கார்டை அல்லது மெனுவைத் தட்டவும்.',
      'guide_step2_title': 'தொழுகை அலாரங்கள்',
      'guide_step2_desc': 'ஒவ்வொரு தொழுகைக்கும் அறிவிப்புகளை ஆன் அல்லது ஆஃப் செய்ய வலதுபுறத்தில் உள்ள சுவிட்சுகளைத் தட்டவும்.',
      'guide_step3_title': 'நேரத்தை மாற்றுக',
      'guide_step3_desc': 'அலார நேரத்தை கைமுறையாக சரிசெய்ய ஏதேனும் தொழுகை வரிசையைத் தட்டவும்.',
      'guide_step4_title': 'செய்தி திருத்தம்',
      'guide_step4_desc': 'செய்தியைத் தனிப்பயனாக்க அல்லது சுழலும் வாராந்திர செய்திகளைத் தேர்ந்தெடுக்க ஏதேனும் தொழுகை வரிசையை நீண்ட நேரம் அழுத்தவும்.',
      'got_it': 'புரிந்தது!',
      'auto_message': 'தானியங்கி செய்தி',
      'custom_message': 'தனிப்பயன் செய்தி',
      'auto_location_enabled': 'தானியங்கி இருப்பிடம் இயக்கப்பட்டது',
      'auto_location_disabled': 'தானியங்கி இருப்பிடம் முடக்கப்பட்டது',
      'last_updated': 'கடைசியாக புதுப்பிக்கப்பட்டது',
      'sound_changed': 'ஒலி மாற்றப்பட்டது',
      'not_updated_yet': 'இன்னும் புதுப்பிக்கப்படவில்லை',
      'updated': 'புதுப்பிக்கப்பட்டது',
      'required_fields': 'தேவையான அனைத்து விவரங்களையும் நிரப்பவும்',
      'message_optional': 'செய்தி (விருப்பத்திற்குரியது)',
      'repeat_pattern': 'மறுமுறை அமைப்பு',
      'Daily': 'தினமும்',
      'Weekdays': 'வார நாட்கள்',
      'Weekends': 'வார இறுதி',
      'Custom': 'தனிப்பயன்',
      'select_time': 'நேரத்தைத் தேர்ந்தெடு',
      'add': 'சேர்',
      'reminder_name': 'நினைவூட்டல் பெயர்',
      'notification_sound': 'அறிவிப்பு ஒலி',
      'perform_prayer': 'தொழுகை',
      'fix_sound': 'ஒலியைச் சரிசெய்',
      'open_settings': 'அமைப்புகளைத் திறக்கவும்',
      'guide_step5_title': 'ஒலி அமைப்புகள்',
      'guide_step5_desc': 'உங்கள் அலாரங்கள் ஒலிக்கவில்லை என்றால், அறிவிப்பு அமைப்புகளைத் திறந்து "Allow playing sound" (ஒலியை அனுமதி) என்பதை ஆன் செய்யவும்.',
      'prayer_location_heading': 'தொழுகை நேரங்கள் & இருப்பிடம்',
      'tap_to_enable_location': 'இருப்பிடத்தை இயக்க தட்டவும்',
      'refreshing_location_prayer_times': 'இருப்பிடம் மற்றும் தொழுகை நேரங்கள் புதுப்பிக்கப்படுகின்றன...',
      'prayer_subtitle': 'தினசரி தொழுகை நேரங்கள் & பாங்கு நினைவூட்டல்கள்',
      'workout_subtitle': 'உடற்பயிற்சி மற்றும் உடலமைப்பு அட்டவணை',
      'meal_subtitle': 'சத்து மற்றும் உணவு நேர நினைவூட்டல்கள்',
      'medicine_subtitle': 'மாத்திரைகள் மற்றும் சுகாதார நினைவூட்டல்',
      'study_subtitle': 'படிப்பு, வாசிப்பு & தேர்வு அட்டவணைகள்',
      'sleep_subtitle': 'தூக்க நேரம் மற்றும் ஓய்வு அட்டவணை',
      'confirm_delete': 'நீக்க விரும்புவது உறுதியா',
      'delete': 'நீக்கு',
      'setup_sample_planner': 'மாதிரி நினைவூட்டல்',
      'clear_all': 'அனைத்தையும் நீக்கு',
      'sample_planner_loaded': 'மாதிரி நினைவூட்டல்கள் ஏற்றப்பட்டன!',
      'load_sample_reminders': 'மாதிரி நினைவூட்டல்களை ஏற்று',
      'samples_already_added': 'மாதிரி நினைவூட்டல்கள் ஏற்கனவே சேர்க்கப்பட்டுள்ளன',
    },
    'ur': {
      'app_title': 'ریمائنڈر ایپ',
      'prayer_planner': 'نماز کا ریمائنڈر',
      'workout_planner': 'ورزش کا ریمائنڈر',
      'meal_planner': 'کھانے کا ریمائنڈر',
      'medicine_planner': 'دوا کا ریمائنڈر',
      'study_planner': 'اسٹڈی ریمائنڈر',
      'snacks_planner': 'اسٹڈی ریمائنڈر',
      'sleeping_planner': 'نیند کا ریمائنڈر',
      'about_app': 'ایپ کے بارے میں',
      'guide': 'گائیڈ',
      'enable_auto_location': 'آٹو لوکیشن',
      'disable_auto_location': 'آٹو لوکیشن غیر فعال کریں',
      'refresh_prayer_times': 'اوقات اپ ڈیٹ کریں',
      'auto_open_on_ring': 'خودکار کھولیں',
      'no_reminders_yet': 'ابھی تک کوئی ریمائنڈر نہیں ہے!',
      'sunrise': 'طلوع آفتاب',
      'next_prayer': 'اگلی نماز',
      'save': 'محفوظ کریں',
      'cancel': 'منسوخ',
      'name': 'نام',
      'time': 'وقت',
      'message': 'پیغام',
      'repeat_days': 'دہرائیں',
      'add_reminder': 'ریمائینڈر شامل کریں',
      'edit_reminder': 'ریمائینڈر میں ترمیم کریں',
      'delete_reminder': 'ریمائنڈر حذف کریں',
      'select_sound': 'آواز منتخب کریں',
      'done': 'مکمل',
      'language': 'زبان',
      'select_language': 'زبان منتخب کریں',
      'Fajr': 'فجر',
      'Dhuhr': 'ظہر',
      'Asr': 'عصر',
      'Maghrib': 'مغرب',
      'Isha': 'عشاء',
      'Sunrise': 'طلوع آفتاب',
      'reminder_deleted': 'ریمائنڈر حذف ہو گیا',
      'guide_title': 'نماز گائیڈ',
      'guide_step1_title': 'آٹو لوکیشن',
      'guide_step1_desc': 'درست مقامی نماز کے اوقات کے لیے اوپری کارڈ یا مینو پر ٹیپ کریں۔',
      'guide_step2_title': 'نماز کے الارم',
      'guide_step2_desc': 'ہر نماز کے لیے نوٹیفیکیشن آن یا آف کرنے کے لیے دائیں جانب والے بٹنز کو ٹوگل کریں۔',
      'guide_step3_title': 'وقت تبدیل کریں',
      'guide_step3_desc': 'الارم کے وقت کو دستی طور پر ایڈجسٹ کرنے کے لیے کسی بھی نماز کی قطار پر ٹیپ کریں۔',
      'guide_step4_title': 'پیغام تبدیل کریں',
      'guide_step4_desc': 'پیغام کو اپنی مرضی کے مطابق بنانے یا ہفتہ وار گھومنے والے پیغامات کو منتخب کرنے کے لیے کسی بھی نماز کی قطار پر دیر تک دبا کر رکھیں۔',
      'got_it': 'سمجھ گیا!',
      'auto_message': 'خودکار پیغام',
      'custom_message': 'حسب ضرورت پیغام',
      'auto_location_enabled': 'آٹو لوکیشن فعال کر دیا گیا ہے',
      'auto_location_disabled': 'آٹو لوکیشن غیر فعال کر دیا گیا ہے',
      'last_updated': 'آخری بار اپ ڈیٹ کیا گیا',
      'sound_changed': 'آواز تبدیل ہو گئی',
      'not_updated_yet': 'ابھی تک اپ ڈیٹ نہیں ہوا',
      'updated': 'اپ ڈیٹ کیا گیا',
      'required_fields': 'برائے مہربانی تمام مطلوبہ فیلڈز پُر کریں',
      'message_optional': 'پیغام (اختیاری)',
      'repeat_pattern': 'دہرانے کا پیٹرن',
      'Daily': 'روزانہ',
      'Weekdays': 'ہفتے کے دن',
      'Weekends': 'ہفتے کا آخر',
      'Custom': 'حسب ضرورت',
      'select_time': 'وقت منتخب کریں',
      'add': 'شامل کریں',
      'reminder_name': 'ریمائنڈر کا نام',
      'notification_sound': 'نوٹیفیکیشن کی آواز',
      'perform_prayer': 'نماز ادا کریں',
      'fix_sound': 'الارم آواز درست کریں',
      'open_settings': 'ترتیبات کھولیں',
      'guide_step5_title': 'آواز کی ترتیبات',
      'guide_step5_desc': 'اگر آپ کے அலாரங்கள் ஒலிக்கவில்லை என்றால், அறிவிப்பு அமைப்புகளைத் திறந்து "Allow playing sound" (ஒலியை அனுமதி) என்பதை ஆன் செய்யவும்.',
      'prayer_location_heading': 'نماز کے اوقات اور مقام',
      'tap_to_enable_location': 'مقام کو فعال کرنے کے لیے ٹیپ کریں',
      'refreshing_location_prayer_times': 'مقام اور نماز کے اوقات اپ ڈیٹ ہو رہے ہیں...',
      'prayer_subtitle': 'روزانہ کے اوقاتِ نماز اور اذان کے ریمائنڈرز',
      'workout_subtitle': 'ورزش اور فٹنس کے اوقات',
      'meal_subtitle': 'غذائیت اور کھانے کے اوقاتِ ریمائنڈر',
      'medicine_subtitle': 'ادویات اور صحت کی دیکھ بھال',
      'study_subtitle': 'پڑھائی، مطالعہ اور امتحانات کے اوقات',
      'sleep_subtitle': 'سونے کا وقت اور نیند کا دورانیہ',
      'confirm_delete': 'کیا آپ واقعی حذف کرنا چاہتے ہیں',
      'delete': 'حذف کریں',
      'setup_sample_planner': 'نمونہ ریمائنڈر',
      'clear_all': 'تمام حذف کریں',
      'sample_planner_loaded': 'نمونہ ریمائنڈرز کامیابی سے شامل ہو گئے!',
      'load_sample_reminders': 'نمونہ ریمائنڈرز لوڈ کریں',
      'samples_already_added': 'نمونہ ریمائنڈرز پہلے سے شامل ہیں',
    }
  };
}
